path: G:\oidv4_toolkit\OIDv4_ToolKit\OID\Dataset\  # dataset root dir
train: train\  # train images (relative to 'path')
val: train\  # val images (relative to 'path')

# Classes
names:
  0: Car
  1: Vehicle registration plate